### ISSUE TITLE
v0.0.3 Roadmap

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu#1286]
### Buffer Manager
- [x] Single variable-sized buffer pool

### Data Import
- [x] Copy from Multiple Files and Globs
- [ ] Copy from Python libraries (Pandas and Numpy)
- [ ] Allow Copy to be executed multiple times

### Query optimizer
- [x] Column-lifetime optimizer (Projection pushdown)
- [x] Prune unnecessary hash joins
- [x] ASP optimizer
- [x] Factorization-aware dptable
- [x] Improve join order optimization

### Graph data science
- [x] [PyG remote backend](https://github.com/pyg-team/pytorch_geometric/issues/4806) integration 

### Data types and functions
- [x] Tensor. More arrow/parquet compatible data types: float, int32, int16
- [x] Collect
- [ ] Coalesce
