### ISSUE TITLE
Release v0.0.5 Roadmap

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#1637]
- Storage
	- [ ] NodeGroup
	- [ ] Bit packing compression
	- [ ] Copy Node & Rel using processor architecture
	- [ ] CSV reader that doesn't depend on arrow
- DataType
	- [x] Map
	- [x] Union / Unstructured
- Functions
	- [x] More and more and more ...
- Processor
	- [ ] Try to be feature complete for open Cypher 9 in general #1644  
	- [ ] openCypher tck #1663 
- Client API
	- [x] Rust
	- [x] Java
- Demo
	- [ ] NodeJS example

**Comment by prrao87** [comment]
I have a question around how graph visualization will be incorporated into the roadmap, and how it is focused on developer experience — for Kùzu truly to be the DuckDB of graphs, the ability to iterate, experiment and test out ideas quickly is key, and this is deeply linked with the question of how one can get visual feedback on what their graph  contains once the data is ingested. No need for a lot of flexibility and customization on the visualization -- just a simple web server spun up that answers the user's query should suffice. I hope this will be considered for future releases!

**Comment by prrao87** [comment]
[kglab](https://github.com/DerwenAI/kglab) used PyVis, a Python wrapper around Vis.js to perform basic graph visualization -- something like this would be very useful to gain new users in Kùzu, imo.

**Comment by th5** [comment]
Visualization is our highest priority missing feature. Amazon's Neptune Graph Explorer might be a good drop-in solution. [https://github.com/aws/graph-explorer](https://github.com/aws/graph-explorer)

@prrao87 Thanks for the recommendation on kglab and PyVis. We've been looking for a graph visualization solution for our internal tech stack. Ideally something like this would come with our graph db.
