### ISSUE TITLE
Broken LDBC SNB Interactive Complex Queries

### ISSUE THREAD

**Issue by aziz-mu** [kuzudb/kuzu#1667]
I'm adding some interactive complex queries to the testing files in PR #1664 . Reference implementations can be found in https://github.com/ldbc/ldbc_snb_interactive_impls/blob/main/cypher/queries/interactive-complex-10.cypher, although the individual queries need to be "translated" to Kuzu's Cypher. Here's a list of the queries that currently aren't working and what needs to be changed in order to make them work: 
- [ ]  IC1: This query has a bug with the CASE WHEN, see issue https://github.com/kuzudb/kuzu/issues/1710
- [ ] IC5: Requires correlated optional match.
- [x] IC7: Can't be implemented until issue #1665 is fixed for collect(), as well as issue #1666 
- [x] IC9: Can't be implemented until issue #1665 is fixed for unwind()
- [ ] IC10: The issue with this query is the `size([p IN posts WHERE ...])` line. This can be worked around easily if either (i) correlated optional match is implemented, or if (ii) issue #1665 is fixed for unwind(), or if (iii) `COUNT { subquery }` syntax is implemented. There might be another workaround, but I couldn't find it after working for an hour or so on it. 
- [ ] IC13(b). IC13 is implemented, but according to SNB v2.0, there should be 2 test cases - one where a path is guaranteed (IC13(a)) and one where one isn't (IC13(b)). Currently only IC13(a) is implemented, IC13(b) needs correlated optional match (or something else to return 0 when a shortest path isn't found)
- [ ] IC14: I don't know exactly what needs to be implemented for IC14 to work, but at the very least we need weighted shortest paths. 

All of these queries might have workarounds that don't involve the posted, please let me know if you find a different way of implementing any of these.
