### ISSUE TITLE
Support COPY TO statement

### ISSUE THREAD

**Issue by rfdavid** [kuzudb/kuzu#1692]
### Proposal

This feature will enable users to export query results to either CSV or PARQUET files using our current `COPY` command. In the same way, we already perform `COPY FROM`, the idea is to use the same statement using `COPY TO`, similar to [DuckDB Copy](https://duckdb.org/docs/sql/statements/copy.html).

### Examples

Write node table Person to `person.csv` 
`COPY Person TO "person.csv"`

Add HEADER and DELIMITER properties
`COPY Person TO "person.csv" (HEADER=true, DELIM='|');`

Write a specific query result to `result.parquet`
`COPY "MATCH (a:person) RETURN a.name" TO "result.parquet"`

**Todo**

- [ ] Implement `writeToParquet` API
- [ ] Implement `COPY TO` without query and additional properties
- [ ] Support additional properties / queries (tbd)
