### ISSUE TITLE
Release v0.0.7 Roadmap

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#1798]
- Storage
	- [ ] Node group-based storage
	- [ ] Constant compression
	- [ ] Bit-packing for numeric values
	- [ ] Copy Node & Rel using processor architecture
- Cypher
	- [ ] openCypher tck #1663 
- UDF
	- [x] Allow user to define scalar function
- Copy To
	- [x] Copy to csv
	- [ ] Copy to parquet
- COPY from remote file system
- Upsert
- Multi-label create/set/delete
