### ISSUE TITLE
V0.0.9 Roadmap

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#1973]
- Copy & Storage
	- [x] Copy rel pipeline reuse task schedular
	- [x] Compression: integer bitpacking
- Feature
	- [x] Direct scan from csv & parquet
	- [x] Defining rel table over multiple src/dst node table pairs #1888 
	- [x] Transaction statement
	- [x] Unsigned integer
- Reader
	- [x] Replace arrow csv reader with our owns.
	- [x] Parallel csv reader
	- [x] Replace arrow parquet reader with our owns.
- Performance  
	- [x] Projection push down for recursive join

**Comment by andyfengHKU** [comment]
Further notes on release

Doc

- [ ] DataTypes
- [ ] DDL with rel group
- [ ] Transaction statement
- [ ] Direct scan
- [ ] Copy to parquet

Experiment

- [ ] Copy performance on both node table and rel table
- [ ] Data size on disk (potential full column scan performance)
