### ISSUE TITLE
Roadmap V0.1.0

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu#2250]
## Major Internal Changes and Improvements
- [x] Node group based storage: rel tables.
- [ ] Hash index rework: improving data ingestion performance.
- [x] Remove arrow lib as the third-party dependency. (but still keeping c data interface for exporting and future data importing)
- [x] Improved export to CSV files, including performance improvements.
- [x] String compression: dictionary encoding.

## Features
- [x] Export tables to parquet files.
- [ ] More complete data type support: timestamp w/ timezone, timestamp w/ ms or seconds. (Error if loading unsupported data types from Parquet) 
- [x] COPY from python pandas objects.
- [x] Detach DELETE.
- [x] COUNT and EXISTS subquery.
- [ ] [Import/Export database](https://github.com/kuzudb/kuzu/issues/2312).
- [x] Copy partial columns.
- [x] Recursive pattern node filter
- [ ] Recursive pattern trail semantic
- [x] Read after update
- [x] Return after delete

## Fixes
- [x] https://github.com/kuzudb/kuzu/issues/1310
