### ISSUE TITLE
Missing features in Copy From/To

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#2251]
## Copy-to csv
- [x] Support copy fixed-list to csv.
- [x] Support copy union to csv.
- [x] Support copy to with options. (https://github.com/kuzudb/kuzu/issues/2439)

## Copy-to parquet
- [x] Support copy to with options. (https://github.com/kuzudb/kuzu/issues/2638)
- [x] Support fixed-list, MAP, timezone, interval datatype.

## Copy-from parquet
- [x] Support fixed-list, MAP, timezone, interval,timestamp datatype.
- [x] Support implicit casting while reading from parquet column with a different column type. (https://github.com/kuzudb/kuzu/issues/2345)
- [x] Support more encoding/compression scheme

## Utility table functions
- [ ] parquet_metadata: used to query the metadata contained within a Parquet file, which reveals various internal details of the Parquet file such as the statistics of the different columns.
- [ ] parquet_schema: used to query the internal schema contained within a Parquet file.
- [ ] parquet_file_metadata: used to query file-level metadata such as the format version and the encryption algorithm used.
- [ ] parquet_kv_metadata: used to query custom metadata defined as key-value pairs.

**Comment by andyfengHKU** [comment]
I'm closing this issue because we don't seem to require these parquet table functions yet.
