### ISSUE TITLE
Upcoming releases roadmap

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#4029]
### Description

This issue keeps track of the main features we should deliver in the upcoming releases:

### Features
- [ ] Full text search
- [ ] WASM
- [ ] Graph algorithm package
- [ ] Unify REL TABLE GROUP with REL TABLE #3627
- [ ] Vector index

**Comment by prrao87** [comment]
Shall we rename this to 0.6.0 release roadmap? TO be more specific.

**Comment by andyfengHKU** [comment]
I don't mind, but @ray6080 apparently thinks some of the features should be delivered in v0.5.1

**Comment by ray6080** [comment]
> I don't mind, but @ray6080 apparently thinks some of the features should be delivered in v0.5.1

I think it's unclear what's the scope of v0.6.0 yet. We need to discuss this internally first.

**Comment by mxwli** [comment]
The CSV Sniffing PR Fixes Decimal Comparison as well. It should be released.

**Comment by prrao87** [comment]
@ray6080 I made some minor modifications to the bullets above, please review.

**Comment by andyfengHKU** [comment]
This was originally for v0.7.0 but we don't seem to still have the record. I'm closing this and open a new one for v0.8.0
