### ISSUE TITLE
Feature: Full text search todo

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#4564]
### API

C++

### Description

- [ ] Support copy in manual transactions.  
- [ ] Support optional parameters in standalone call functions (e.g., stopwords, stem).  
- [ ] Support virtual tables.  
- [ ] Disallow users from querying virtual tables/properties and helper functions/internal FTS functions.  
- [ ] Support multi-statement queries in the testing framework.  
- [ ] Support querying a subset of columns in `query_fts_index()`.  
- [ ] Output nodes with null scores.  
- [ ] Disallow users from dropping a property that has an index on it.  
- [ ] Remove `edgeCompute` to compute the scores and do this in a single-threaded manner.  
- [ ] Once `edgeCompute` is removed, pass terms in a sparse map (e.g., `ValueVector`) instead of using a semi-masker. This avoids redundant construction and looping.  
- [ ] Optimize the lookup of term keys in `queryFTS`, we can probably do primary key lookup in such cases.  
- [ ] Optimize the storage of stop-words, we may only need to store the stop-words table only once.
