### ISSUE TITLE
0.8.0 Release

### ISSUE THREAD

**Issue by andyfengHKU** [kuzudb/kuzu#4567]
This issue keeps track of the planned features for the upcoming 0.8.0 release.

## Features
- [x] WASM (Chang)
    - [x] Release pipeline in CI
    - [x] Docs generation in CI
    - [x] Creating and merging PR to master
- [x] Full-text search
  - [x] Utility to functions to see indices that have been created with our without the extension installation (Ziyi)
  - [x] Explorer Visual Changes Research (Prashanth)
  - [x] https://github.com/kuzudb/kuzu/issues/4760
  - [x] https://github.com/kuzudb/kuzu/issues/4762
- [x] Deprecate `REL TABLE GROUP` (Xiyang)
    - [x] Merge PR to master
    - [x] Changes to Explorer (Chang)
    - [x] From Langchain + LlamaIndex (Prashanth)
    - [x] Add support for ALTER TABLE (Royi)
- [x] Skip errors from DataFrame scans
- [x] Support skip/limit options for DataFrame scan. https://github.com/kuzudb/kuzu/pull/4662

## APIs
- [x] https://github.com/kuzudb/kuzu/issues/4582 (Chang)
- [x] https://github.com/kuzudb/kuzu/issues/4708 (Royi)
- [x] https://github.com/kuzudb/kuzu/issues/4575 (Royi)

## Performance Optimizations
- [x] Parallel Hash Aggregate (Ben) #4655 
- [x] Hyperloglog Optimizer

## Bugfixes
- [x] https://github.com/kuzudb/kuzu/issues/4778 (Guodong)
- [x] https://github.com/kuzudb/kuzu/issues/4783 (Guodong)
- [x] https://github.com/kuzudb/kuzu/issues/4777 (Guodong)
- [x] https://github.com/kuzudb/kuzu/issues/4724 (Guodong)
- [x] https://github.com/kuzudb/kuzu/issues/4716 (Guodong)
- [x] https://github.com/kuzudb/kuzu/issues/4715 (Guodong)
- [x] https://github.com/kuzudb/kuzu/issues/4189 (Guodong)
- [x] https://github.com/kuzudb/kuzu/issues/4540 (Guodong)
- [x] https://github.com/kuzudb/kuzu/issues/4459 (Guodong)
- [x] https://github.com/kuzudb/kuzu/issues/4301
- [x] https://github.com/kuzudb/kuzu/issues/4731 (Guodong)
- [x] https://github.com/kuzudb/kuzu/issues/4730 (Royi)
- [x] https://github.com/kuzudb/kuzu/issues/4719 (Royi)
- [x] https://github.com/kuzudb/kuzu/issues/4431 (Royi/Chang)
- [x] https://github.com/kuzudb/kuzu/issues/4740 (Ziyi)
- [x] ~~https://github.com/kuzudb/kuzu/issues/4714 (Ziyi)~~
- [x] https://github.com/kuzudb/kuzu/issues/4566 (Ziyi/Howe)
- [x] https://github.com/kuzudb/kuzu/issues/4550 (Chang)
- [x] https://github.com/kuzudb/kuzu/issues/4385 (Chang)
- [x] https://github.com/kuzudb/kuzu/issues/4756 (Ziyi)
- [x] https://github.com/kuzudb/kuzu/issues/4761 (Ziyi)
- [x] https://github.com/kuzudb/kuzu/issues/4767 (Xiyang)
- [x] https://github.com/kuzudb/kuzu/issues/4768 (Xiyang)
- [x] https://github.com/kuzudb/kuzu/issues/4541 (Xiyang)
- [x] https://github.com/kuzudb/kuzu/issues/4772 (Xiyang)
- [x] https://github.com/kuzudb/kuzu/issues/4782 (Xiyang)
- [x] https://github.com/kuzudb/kuzu/issues/4615 (Xiyang)
- [x] https://github.com/kuzudb/kuzu/issues/4814 (Royi)
- [ ] https://github.com/kuzudb/kuzu/issues/4749 (Chang)

## Documentation
- [x] WASM (Chang) https://github.com/kuzudb/kuzu-docs/pull/331
- [x] FTS (Ziyi) https://github.com/kuzudb/kuzu-docs/pull/332
- [x] Skip errors from pandas scans (Royi) https://github.com/kuzudb/kuzu-docs/pull/334
- [x] Skip/limit parameters for Pandas scan (Royi/Prashanth) https://github.com/kuzudb/kuzu-docs/pull/338 
- [x] Limit/skip number as parameter expression (Ziyi)https://github.com/kuzudb/kuzu-docs/issues/333
- [x] Deprecate `REL TABLE GROUP` (Ziyi) https://github.com/kuzudb/kuzu-docs/pull/349
- [x] Java API (auto-generated)
- [x] Import/export databases with indexes (Ziyi) https://github.com/kuzudb/kuzu-docs/pull/340
- [x] Add doc for type casting when scanning from relational database (Ziyi) https://github.com/kuzudb/kuzu-docs/issues/326
- [x] https://github.com/kuzudb/kuzu-docs/issues/346 (Ziyi)

## Testing
- [x] WASM Testing (Chang should fill this in)
- [x] FTS Testing
   - [x] Test CLI syntax highlighting 
- [x] Skip errors from pandas scans
- [x] Deprecate `REL TABLE GROUP` in Langchain and LlamaIndex (Prashanth)

## Content
- [x] Release Blog (Guodong draft)
    - [x] WASM (Chang)
    - [x] FTS (Ziyi)
    - [x] Rel group changes
    - [x] Performance optimization
- [ ] WASM Blog (Semih + Chang + Prashanth)
