### ISSUE TITLE
Todo in DDL

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu#735]
- [x] Remove metadata.json completely, and use DDL + COPY CSV to load dataset.
- [x] Update desing document for loading dataset.
- [x] Node/RelLabel has different meaning in front end and back end, we should unify the meaning of node/relLabel
