### ISSUE TITLE
Checkpointing Enhancements

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#771]
Our checkpointing mechanism needs several enhancements to write more data in bulk.
- [ ] Multi element updates and pushBack to DiskArray (https://github.com/graphflowdb/graphflowdb/issues/716)
- [ ] Make InMemDiskArray use BM to store array pages (https://github.com/graphflowdb/graphflowdb/issues/717)
- [ ] Implement popBack functionality to DiskArray (https://github.com/graphflowdb/graphflowdb/issues/718)
- [ ] Optimize updates to Unstructured Property Lists, Adjacency Lists, and PropertLists. (https://github.com/graphflowdb/graphflowdb/issues/730)

**Comment by ray6080** [comment]
This is stale now.
