### ISSUE TITLE
Phase1 Todos

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#837]
## Website, Blog, etc.
- [x] Link to final github pages linking to the rest of the documentation on overview page.
- [x] Link our domain names to github pages.
- [x] Check if we can order the sub-pages? 
- [x] Check if the relative links in documentation that used .md work.
- [x] Add a citation on the main page to cite our paper and a general citation for us in general. 
- [x] Link to Phase 2 roadmap in the blog.
- [x]  Get a Kuzu email address and mention it in the blog and on documentation.
- [x] **IMPORTANT**: Double check [CI config](https://github.com/kuzudb/kuzu/settings/actions) after we make the repo public. We need to make sure that the forked repos cannot trigger CI without approval.
## Fixes
- [x] Make the logs optional and not the default when running commands from CLI. When you run a simple CREATE NODE TABLE command, you get 7 log outputs, which is distracting.
- [x] For ONE_ONE, MANY_ONE, ONE_MANY make sure we error if multiple edges are inserted that violate the constraint. That is when an edge u-[R]->v with label R  is being inserted, if the source side of the multiplicity is "ONE", then we need to check that v does not already have an edge with label R. Similarly if the destination side of the multiplicity is "ONE", then we need to check that u does not already have an edge with label R. [Issue 892](https://github.com/graphflowdb/graphflowdb/issues/892)
- [x] CLI :show_rel command. Either explain why when you do show_rel X, you see the _id or remove it from the list.
- [x] CLI: show_node should indicate the primary key of the table.
- [x] Change from/toType in CSV headers to from/toLabel and update Documentation. Discuss with team. 
    We don't even check the header. => We force users to specify if there are multiple labels in src or dst. We force users to not specify if there is a single src/dst label.
- [x] Check what COPY_CSV does if the initial database is not empty. 
- [x] Test # comment behavior in csv files. Is it the prefix set of lines or can we add a comment in the middle of the line? Let's make it the initial set of lines. Or remove comments from CSV files. => We are not supporting comments in CSV.
- [x] numGeneratedProperties -> Remove
- [x] Check if node and rel table names are case sensitive or not in other systems. Currently they are in Kuzu=> We can remain sensitive.
- [x] Last CSV file line has to have a CTRL. Let's be robust against this.
- [x] Do not crash when you are given an empty CSV file. Error with a meaningful error message. Currently the error message is: `Thread CopyCSV exception: The number of fields in the CSV file does not match number of fields expected. Expecting 2 or 4 fields. The CSV file has 0 fields. caught an exception 0x7000087e4000. Setting the exception of the task`
- [x] Check if we should have a way to insert an empty string as a structured or unstructured property.
- [x] Copy From CSV seems to be failing if there are extra columns. It was failing on this:
```
vPerson.csv
AAAAAAAAAAAAAAAAAAAA,1,Bob
Bob,2,AAAAAAAAAAAAAAAAAAAA
eKnows.csv
AAAAAAAAAAAAAAAAAAAA,Bob
when schema was: CREATE NODE TABLE Person(name STRING, spouse STRING, PRIMARY KEY (name))
create REL TABLE Knows (FROM Person TO Person);
```
- [x] Implement storage of deleted tableIDs, so we do not give the same table ID to different tables.
- [x] Move Catalog to be map based instead of tableID based.
- [x] Increase the log level to error CLI does not print those log files in commands.
- [x] Improvements to the shell outputs: https://github.com/graphflowdb/graphflowdb/issues/901
- [x] Fix opened issues related to intersect (#913 ).
- [x] Add somewhere the constraint that RETURN after UPDATE is not supported. (See this: https://github.com/graphflowdb/graphflowdb/pull/945)
- [x] Export to csv and pandas documentation.
- [x] Remove (inMemory: false, defaultPagedBPSizeInMB: 1024, largePagedBPSizeInMB: 512 from the shell output)
- [x] TODOs on [getting-started](https://github.com/graphflowdb/graphflowdb.github.io/blob/documentation/docs/getting-started.md)
- [x] Known crashes:
    - [x] Create a node with NULL as primary key `CREATE (u:User {name: NULL, age:NULL})`
    - [x] Out of range date `RETURN make_date(1111, 1, 32)` #992
    - [x] Using invalid specifier `return date_part('date', Date('1995-01-01'))` #992
    - [x] any number / 0
    - [x] return min(1) #992
    - [x] return null #992 

## Documentation
- [x] Update README.md of the original file to link to the documentation. Also Current README.md requires improvements: 
    - [x] Add our logo there. 
    - [x]  We should always use Kùzu with the umlaut and be careful with cases (e.g., the first line in README writes "kuzu").
    - [x] We should remove the link to the design documents
    - [x] We should keep it very brief and simply link to the documentation's getting-started instead of giving information about the CLI and drivers or benchmark runner. Some of the information there, e.g., benchmark runner can be moved to a Google Doc for now and later to an internal private repo maybe.
    - [x] Add a code of conduct and Reach out to Us part at the end (Semih can do this).
- [x]  Documentation:
  - [x] expressions: overview
  - [x] parameters (inside C++ and Python APIs) (xiyang)
  - [x] query-clauses:  return
  - [x] DDL: Drop Table
  - [x] TODO in the getting-started for pip-install and C++ installation.
  - [x] Normalize all Cypher query clause documenation that uses the example-database.md to start with exactly as in the beginning of [MATCH documentation](https://github.com/kuzudb/kuzudb.github.io/blob/documentation/docs/cypher/query-clauses/match.md)
  - [x] [Parameters](https://github.com/kuzudb/kuzudb.github.io/blob/documentation/docs/cypher/expressions/parameters.md) does not seem to belong under expressions. Find another location for it.
  - [x] Add documentation for EXPLAIN and PROFILE somewhere.
  - [x]  Remove the running example png if needed from here: https://github.com/kuzudb/kuzudb.github.io/blob/main/docs/cypher/query-clauses/running-example.png and update all references to it, if necessary.
  - [x] Check that the overview page under Data Manipulation is published after publishing.
