### ISSUE TITLE
List of Features for Phase 1

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/kuzu#85]
Just to keep our thoughts a bit organized, I am listing the set of features that needs to be implemented before we can show the system to someone:

**Phase 1 Features**
- [x] Unstructured Properties (Storage, QP)
- [x] Nulls with null bits (QP)
- [x] Remove existing work on Updates (Storage, Frontend)
- [x] Remove LOAD CSV (for batch updates), CREATE, DELETE, REMOVE
- [x] Variable-length joins with minimum and maximum (min...max). (QP) (https://github.com/graphflowdb/graphflowdb/issues/525 the faster version could go to phase 2)
- [x] exists(property) (Frontend, QP)
- [x] Sorting for cyclic queries (QP) + WCO joins.
- [x] Aggregations (With special operators for aggregating over nodes) (QP, Frontend)
- [x] DISTINCT, UNION, and UNION ALL
- [x] LIMIT, SKIP
- [x] ORDER BY (ASC/DESC)
- [x] WITH clause
- [x] Optional MATCH (Frontend, QP)
- [x] Profiler/Explain (Frontend)
- [x] CLI to issue queries
- [x] Scalable RETURN all unstructured properties of a node/rel. #416
- [x] primary key #216 
- [x] Cross Product
- [x] Memory-only columns/adjacency lists.
- [x] A robust memory or buffer manager that will allow us to not fail when an operator uses a lot of memory. Change any operator that accumulates data to use buffer manager. Make some disk-based FactorizedTable and OrderBy.-
- [x] String Functions #538 
- [x] Numeric Functions #539 
- [x] List data type & List functions (https://github.com/graphflowdb/graphflowdb/issues/535)
- [x] Loader and Storage TODOs https://github.com/graphflowdb/graphflowdb/issues/504
- [x] Add a way to ingest parameters to queries.
- [x] Main Client Drivers? We could ask JPMorgan but I think it makes sense to have Java and Python to start with
- [x] Transactions Phase 1: https://github.com/graphflowdb/graphflowdb/issues/560
- [x] DDL Support:  CREATE NODE/REL TABLE and COPY FROM CSV
   - [x] DROP TABLES
   - [x] SHOW TABLES;
   - [x] DESCRIBE TABLE
- [x] Exists & Semi Hash Join
- [x] Optional Match & Left Hash Join
- [x] Multiple Join Nodes
- [x] Binary ASP Join
- [x] Multiway ASP Join (Worst Case Optimal Joins)
- [x] IndexScan (scan of nodes based on primary key (and refactor of hash indices))
- [x] Configure bmSize and numThreads from API and CLI (https://github.com/graphflowdb/graphflowdb/issues/773)
- [x] Pip installament: pip install kuzudb
- [x] Multi-thread execution in Python APIs (https://github.com/graphflowdb/graphflowdb/issues/561)
- [x] User Documentation: How to set up and use the system, examples of queries, supported Cypher clauses.
- [x] Performance optimizations: This includes a broad range of optimizations we might want to do from expression rewriting, to buffer manager optimizations, to data ingest optimizations, among others we will think of. This and benchmarks against other systems item are related because we want to ensure our scalability and performance is good enough compared to others. So we need to obtain performance until we look good against other systems. An example is this: #583.
- [x] Testing of the system: This involves setting up many end-to-end tests and can also be part of setting up a benchmarking infrastructure with a cron job that keeps track of the system's daily performance. I like what was desribed here.)
- [x] Usability Features #433 
- [x] Website construction
- [x] Logo design
